-- cards: user_id, card_description 컬럼 추가 및 FK 설정
ALTER TABLE "public"."cards"
  ADD COLUMN IF NOT EXISTS "user_id" uuid,
  ADD COLUMN IF NOT EXISTS "card_description" text;

ALTER TABLE "public"."cards"
  ADD CONSTRAINT "cards_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id),
  ADD CONSTRAINT "cards_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);

-- categories 테이블 신규 생성
CREATE TABLE IF NOT EXISTS "public"."categories" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "category_code" text,
  "amount_subject" text,
  "category_name" text,
  "company_id" bigint,
  CONSTRAINT categories_pkey PRIMARY KEY (id)
);

-- receipts: user_id uuid 타입, amount numeric, payment_date timestamptz, FK 추가
-- (기존 테이블이 bigint user_id였다면 아래 주석을 해제 후 실행)
-- ALTER TABLE "public"."receipts" ALTER COLUMN "user_id" TYPE uuid USING user_id::text::uuid;
-- ALTER TABLE "public"."receipts" ALTER COLUMN "amount" TYPE numeric;
-- ALTER TABLE "public"."receipts" ALTER COLUMN "payment_date" TYPE timestamp with time zone;

ALTER TABLE "public"."receipts"
  ADD CONSTRAINT IF NOT EXISTS "receipts_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id),
  ADD CONSTRAINT IF NOT EXISTS "receipts_trip_id_fkey" FOREIGN KEY (trip_id) REFERENCES trips(id),
  ADD CONSTRAINT IF NOT EXISTS "receipts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id);

-- _2 임시 테이블 제거 (존재하는 경우)
DROP TABLE IF EXISTS "public"."cards_2";
DROP TABLE IF EXISTS "public"."receipts_2";
